apiVersion: v1
kind: Pod
metadata:
  name: image-resolver-api
  labels:
    app: api
spec:
  containers:
  - name: image-resolver-api
    image: shekhargulati/image-resolver-api
    env:
      - name: "IMAGE_CACHE_ENABLED"
        value: "true"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379