apiVersion: v1
kind: Pod
metadata:
  name: image-resolver-api
  labels:
    app: api
spec:
  containers:
  - name: image-resolver-api
    image: shekhargulati/image-resolver-api
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  initContainers:
  - name: init-setup
    image: busybox
    command: ['sh','-c', 'sleep  30'] 