apiVersion: v1
kind: Service
metadata:
  name: image-resolver-api-svc
spec:
  selector:
    app: api
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31001
    targetPort: 8080
    protocol: TCP
